# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160617_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentdate', models.DateTimeField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice')),
            ],
        ),
        migrations.AlterField(
            model_name='user_details',
            name='age',
            field=models.IntegerField(),
        ),
    ]
